CREATE TABLE Tip (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(200) NOT NULL,
  url VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  craeted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);